"""empty message

Revision ID: 71d58c85cce8
Revises: eac8526d377c
Create Date: 2021-04-15 18:14:47.986876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d58c85cce8'
down_revision = 'eac8526d377c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Venue', 'venue')
    op.rename_table('Artist', 'artist')
    op.alter_column('shows', 'Venue_id', nullable=False, new_column_name='venue_id')
    op.alter_column('shows', 'Artist_id', nullable=False, new_column_name='artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('venue', 'Venue')
    op.rename_table('artist', 'Artist')
    op.alter_column('shows', 'venue_id', nullable=False, new_column_name='Venue_id')
    op.alter_column('shows', 'artist_id', nullable=False, new_column_name='Artist_id')

    # ### end Alembic commands ###
