"""empty message

Revision ID: 78168b7372f2
Revises: 9cc8ec673322
Create Date: 2021-04-15 20:29:43.620419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78168b7372f2'
down_revision = '9cc8ec673322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
