"""empty message

Revision ID: 7e78c1b09e86
Revises: 8a6894d41600
Create Date: 2021-04-06 14:54:32.070252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e78c1b09e86'
down_revision = '8a6894d41600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE "Artist" SET seeking_venue = false WHERE seeking_venue IS NULL')
    op.alter_column('Artist', 'seeking_venue', nullable=False)               
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
